version: '3.2'
services:
  remind:
    image: ${NCP_CONTAINER_REGISTRY_PUBLIC_ENDPOINT}/${NCP_CONTAINER_REGISTRY_IMAGE}
    container_name: ${NCP_CONTAINER_REGISTRY_IMAGE}
    restart: always
    env_file:
      - .env
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - type: bind
        source: /root/.env
        target: /.env