version: '3.2'
services:
  remind:
    image: ${NCP_CONTAINER_REGISTRY_PUBLIC_ENDPOINT}/${NCP_CONTAINER_REGISTRY_IMAGE}
    container_name: ${NCP_CONTAINER_REGISTRY_IMAGE}
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - type: bind
        source: /root/.env
        target: /.env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]